import { NextRequest,NextResponse } from "next/server";
import { randomUUID } from "node:crypto";
import { currentWallet } from "@/lib/auth";
import { dbEnabled,query } from "@/lib/db";
import { rateLimit } from "@/lib/rate-limit";
const GMGN_BASE="https://gmgn.ai/defi/router/v1/sol/tx";
export async function POST(request:NextRequest){
 if(process.env.LIVE_TRADING_ENABLED!=="true")return NextResponse.json({error:"Live trading is disabled. Set LIVE_TRADING_ENABLED=true after testing."},{status:403});if(!process.env.GMGN_API_KEY)return NextResponse.json({error:"GMGN_API_KEY is not configured"},{status:503});
 const wallet=await currentWallet();if(!wallet)return NextResponse.json({error:"Privy authentication with a Solana wallet is required"},{status:401});const rl=rateLimit(`trade:${wallet}`,10,60000);if(!rl.ok)return NextResponse.json({error:"Too many trade requests",retryAfter:rl.retryAfter},{status:429});
 try{const body=await request.json() as {tokenIn:string;tokenOut:string;amount:string;fromAddress:string;slippage?:number;antiMev?:boolean;fee?:number;tokenId?:string;side?:"BUY"|"SELL"};if(body.fromAddress!==wallet)return NextResponse.json({error:"fromAddress must match the authenticated Privy wallet"},{status:403});if(!body.tokenIn||!body.tokenOut||!body.amount)return NextResponse.json({error:"tokenIn, tokenOut and amount are required"},{status:400});const amount=BigInt(body.amount);if(amount<=0n)return NextResponse.json({error:"amount must be positive"},{status:400});const clientId=request.headers.get("idempotency-key")||randomUUID();
 if(dbEnabled()){const prior=await query<any>(`SELECT id,status,tx_hash FROM trades WHERE wallet=$1 AND client_id=$2 LIMIT 1`,[wallet,clientId]);if(prior.rowCount)return NextResponse.json({tradeId:prior.rows[0].id,status:prior.rows[0].status,hash:prior.rows[0].tx_hash,idempotent:true});}
 const slippage=Math.max(.1,Math.min(50,Number(body.slippage??10)));const url=new URL(`${GMGN_BASE}/get_swap_route`);url.searchParams.set("token_in_address",body.tokenIn);url.searchParams.set("token_out_address",body.tokenOut);url.searchParams.set("in_amount",amount.toString());url.searchParams.set("from_address",wallet);url.searchParams.set("slippage",String(slippage));url.searchParams.set("swap_mode","ExactIn");if(body.antiMev)url.searchParams.set("is_anti_mev","true");if(body.fee!==undefined)url.searchParams.set("fee",String(Math.max(0,body.fee)));
 const response=await fetch(url,{headers:{"x-route-key":process.env.GMGN_API_KEY},cache:"no-store"});const data=await response.json();if(!response.ok||data.code!==0)return NextResponse.json({error:"GMGN route request failed",details:data},{status:response.status||502});let tradeId=clientId;if(dbEnabled()){const row=await query<{id:string}>(`INSERT INTO trades(client_id,wallet,token_id,token_address,chain,side,amount_raw,status,metadata) VALUES($1,$2,$3,$4,'solana',$5,$6,'ROUTED',$7) RETURNING id`,[clientId,wallet,body.tokenId||body.tokenOut,body.tokenOut,body.side||"BUY",amount.toString(),JSON.stringify({slippage,antiMev:Boolean(body.antiMev)})]);tradeId=row.rows[0].id;await query(`INSERT INTO trade_events(trade_id,wallet,event_type,payload) VALUES($1,$2,'ROUTED',$3)`,[tradeId,wallet,JSON.stringify({tokenIn:body.tokenIn,tokenOut:body.tokenOut,amount:amount.toString()})]);}return NextResponse.json({...data,tradeId});}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"route request failed"},{status:500});}}
