"use client";
import { useEffect,useMemo,useState } from "react";
import { Activity,ArrowDownRight,ArrowUpRight,Flame,Search,ShieldCheck,Trophy,Wallet,Zap } from "lucide-react";
import { posts,tokens } from "@/lib/demo";
import { executePaperTrade,portfolioValue } from "@/lib/game";
import type { Holding,Token,Trade } from "@/lib/types";
const fmt=(n:number)=>n>=1e9?`$${(n/1e9).toFixed(1)}B`:n>=1e6?`$${(n/1e6).toFixed(0)}M`:n>=1e3?`$${(n/1e3).toFixed(0)}K`:`$${n.toFixed(n<1?4:2)}`;
const money=(n:number)=>`$${n.toLocaleString(undefined,{maximumFractionDigits:0})}`;
export default function Arena(){
 const [query,setQuery]=useState(""); const [tab,setTab]=useState<"hot"|"gainers"|"social">("hot"); const [balance,setBalance]=useState(10000); const [holdings,setHoldings]=useState<Holding[]>([]); const [trades,setTrades]=useState<Trade[]>([]); const [events,setEvents]=useState<string[]>(["GOAT entered the Arena","POPCAT social score hit 98","WIF volume crossed $60M"]); const [connected,setConnected]=useState(false);
 const filtered=useMemo(()=>tokens.filter(t=>`${t.symbol} ${t.name}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>tab==="gainers"?b.change24h-a.change24h:tab==="social"?b.social-a.social:b.volume-a.volume),[query,tab]);
 const equity=portfolioValue(balance,holdings,tokens);
 function trade(token:Token,side:"BUY"|"SELL"){try{const r=executePaperTrade(balance,holdings,trades,token,side,250);setBalance(r.balance);setHoldings(r.holdings);setTrades(c=>[r.trade,...c].slice(0,12));setEvents(c=>[`${side} $250 ${token.symbol}`,...c].slice(0,8));}catch(e){alert(e instanceof Error?e.message:"Trade failed")}}
 useEffect(()=>{const timer=setInterval(()=>{const t=tokens[Math.floor(Math.random()*tokens.length)];setEvents(c=>[`${t.symbol} is moving on CT`,...c].slice(0,8));},5000);return()=>clearInterval(timer)},[]);
 return <main className="shell"><header className="topbar"><div className="brand"><span className="brand-mark">CT</span><div><strong>MEME ARENA</strong><small>TRADE THE MEMES. BEAT THE TIMELINE.</small></div></div><div className="search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search token, ticker, or CT shill..."/></div><div className="top-actions"><div className="stat"><span>PORTFOLIO</span><b>{money(equity)}</b></div><div className="stat"><span>RANK</span><b>#247</b></div><button className="wallet" onClick={()=>setConnected(v=>!v)}><Wallet size={16}/>{connected?"WALLET READY":"CONNECT"}</button></div></header>
 <div className="layout"><aside className="sidebar"><div className="live-dot"><i/> LIVE ARENA</div>{["Arena","Radar","Leaderboard","Quests"].map((x,i)=><button className={i===0?"nav active":"nav"} key={x}>{i===0?<Zap size={17}/>:i===1?<Activity size={17}/>:i===2?<Trophy size={17}/>:<Flame size={17}/>}<span>{x}</span>{i===2&&<em>1,284</em>}</button>)}<div className="side-card"><ShieldCheck size={18}/><b>PAPER MODE</b><span>No real funds are moved in this build.</span></div></aside>
 <section className="content"><section className="hero"><div><span className="eyebrow">SEASON #01 · SOLANA</span><h1>WELCOME TO<br/><span>THE ARENA.</span></h1><p>Find the hottest memes, read the timeline, trade your thesis, and climb the CT leaderboard.</p></div><div className="hero-badges"><div><b>10K</b><span>STARTING CASH</span></div><div><b>24H</b><span>SEASON ROUND</span></div></div></section>
 <section className="panel"><div className="panel-head"><div><span className="kicker">MARKET RADAR</span><h2>WHAT'S MOVING</h2></div><div className="tabs">{(["hot","gainers","social"] as const).map(x=><button key={x} className={tab===x?"tab active":"tab"} onClick={()=>setTab(x)}>{x==="hot"?"🔥 HOT":x==="gainers"?"↗ GAINERS":"◎ SOCIAL"}</button>)}</div></div><div className="token-grid">{filtered.map(t=><article className="token" key={t.id}><div className="token-top"><span className="emoji">{t.emoji}</span><div><b>{t.symbol}</b><small>{t.name}</small></div><span className={`risk ${t.risk.toLowerCase()}`}>{t.risk}</span></div><div className="price"><strong>{t.price<1?t.price.toFixed(6):t.price.toFixed(2)}</strong><span className={t.change24h>=0?"up":"down"}>{t.change24h>=0?<ArrowUpRight size={14}/>:<ArrowDownRight size={14}/>} {Math.abs(t.change24h).toFixed(1)}%</span></div><div className="mini-grid"><span><b>{fmt(t.mcap)}</b><small>MCAP</small></span><span><b>{fmt(t.volume)}</b><small>VOL 24H</small></span><span><b>{t.social}</b><small>SOCIAL</small></span></div><div className="trade-row"><button className="buy" onClick={()=>trade(t,"BUY")}>BUY $250</button><button className="sell" onClick={()=>trade(t,"SELL")}>SELL $250</button></div></article>)}</div></section>
 <div className="two-col"><section className="panel"><div className="panel-head compact"><div><span className="kicker">CT SHILLS</span><h2>TIMELINE SIGNALS</h2></div><span className="pulse">● LIVE</span></div><div className="feed">{posts.map(p=><div className="post" key={p.id}><div className="avatar">{p.user.slice(0,1)}</div><div><div className="post-meta"><b>{p.user}</b>{p.verified&&<ShieldCheck size={13}/>}<span>{p.handle} · {p.time}m</span></div><p>{p.text}</p><div className="post-stats">♥ {p.likes.toLocaleString()} &nbsp; · &nbsp; ↩ {p.replies}</div></div></div>)}</div></section><section className="panel"><div className="panel-head compact"><div><span className="kicker">LIVE ARENA</span><h2>ACTIVITY</h2></div><span className="pulse">● LIVE</span></div><div className="events">{events.map((e,i)=><div className="event" key={`${e}-${i}`}><i/>{e}<span>{i+1}s</span></div>)}</div><div className="arena-cta"><b>READY TO SHILL?</b><span>Drop your thesis into the Arena and earn social points.</span><button onClick={()=>setEvents(v=>["New shill queued for moderation",...v].slice(0,8))}>+ SHILL A TOKEN</button></div></section></div>
 <section className="bottom-grid"><section className="panel"><div className="panel-head compact"><div><span className="kicker">SEASON #01</span><h2>LEADERBOARD</h2></div><span className="muted">RESET IN 04D 12H</span></div>{["Mika","DegenDesk","SolShill","CTWolf","AnonKing"].map((n,i)=><div className="leader" key={n}><span>#{i+1}</span><b>{n}</b><span className="gain">+{[842,691,544,442,318][i]} pts</span><strong>{[19642,17818,15492,14844,13240][i].toLocaleString()} XP</strong></div>)}</section><section className="panel"><div className="panel-head compact"><div><span className="kicker">DAILY QUESTS</span><h2>EARN YOUR EDGE</h2></div></div>{[["MAKE 3 TRADES","2 / 3","66%","+150 XP"],["FIND A 5% RUNNER","1 / 1","100%","+100 XP"],["POST A SHILL","0 / 1","0%","+200 XP"]].map(q=><div className="quest" key={q[0]}><b>{q[0]}</b><span>{q[1]}</span><div className="bar"><i style={{width:q[2]}}/></div><strong>{q[3]}</strong></div>)}</section></section><div className="disclaimer">CT Meme Arena is a competitive paper-trading prototype. Market data shown here is demo data and should not be treated as financial advice.</div></section></div></main>;
}
