import { cookies, headers } from "next/headers";
import { createHash } from "node:crypto";
import { PrivyClient } from "@privy-io/node";
import { dbEnabled, query } from "@/lib/db";
const PRIVY_COOKIE="privy-token"; const ARENA_COOKIE="ctarena_session";
const hash=(value:string)=>createHash("sha256").update(value).digest("hex");
function appId(){const id=process.env.NEXT_PUBLIC_PRIVY_APP_ID||process.env.PRIVY_APP_ID;if(!id)throw new Error("NEXT_PUBLIC_PRIVY_APP_ID is not configured");return id;}
function client(){const secret=process.env.PRIVY_APP_SECRET;if(!secret)throw new Error("PRIVY_APP_SECRET is not configured");return new PrivyClient({appId:appId(),appSecret:secret});}
async function tokenFromRequest(){const authorization=(await headers()).get("authorization");if(authorization?.startsWith("Bearer "))return authorization.slice(7);return (await cookies()).get(PRIVY_COOKIE)?.value??null;}
export async function currentPrivyUser(){const token=await tokenFromRequest();if(!token)return null;try{return await client().utils().auth().verifyAuthToken(token);}catch{return null;}}
export async function currentUser(){const claims=await currentPrivyUser();if(!claims)return null;const user=await client().users()._get(claims.user_id);const accounts=user.linked_accounts as any[];const wallet=accounts.find(a=>a.type==="wallet"&&a.chain_type==="solana");const email=accounts.find(a=>a.type==="email");const google=accounts.find(a=>a.type==="google_oauth");const twitter=accounts.find(a=>a.type==="twitter_oauth");return {claims,user,wallet:wallet?.address??null,walletId:wallet?.id??null,email:email?.address??null,google:google?.subject??null,twitter:twitter?.subject??null,twitterUsername:twitter?.username??null,avatarUrl:twitter?.profile_picture_url??twitter?.profilePictureUrl??null};}
export async function currentWallet(){const current=await currentUser();if(current?.wallet){if(dbEnabled())await query(`INSERT INTO users (privy_user_id,wallet,email,google_subject,twitter_subject,twitter_username,avatar_url) VALUES ($1,$2,$3,$4,$5,$6,$7) ON CONFLICT (privy_user_id) DO UPDATE SET wallet=EXCLUDED.wallet,email=EXCLUDED.email,google_subject=EXCLUDED.google_subject,twitter_subject=EXCLUDED.twitter_subject,twitter_username=COALESCE(EXCLUDED.twitter_username,users.twitter_username),avatar_url=COALESCE(EXCLUDED.avatar_url,users.avatar_url),updated_at=NOW()`,[current.claims.user_id,current.wallet,current.email,current.google,current.twitter,current.twitterUsername,current.avatarUrl]);return current.wallet;}if(!dbEnabled())return null;const session=(await cookies()).get(ARENA_COOKIE)?.value;if(!session)return null;const result=await query<{wallet:string}>(`SELECT wallet FROM wallet_sessions WHERE token_hash=$1 AND revoked_at IS NULL AND expires_at>NOW()`,[hash(session)]);return result.rows[0]?.wallet??null;}
export async function requireWallet(){const wallet=await currentWallet();if(!wallet)throw new Error("Authenticated Privy Solana wallet required");return wallet;}
export async function requirePrivyUser(){const user=await currentUser();if(!user)throw new Error("Privy authentication required");return user;}
export async function logout(){const jar=await cookies();jar.set(PRIVY_COOKIE,"",{httpOnly:true,secure:process.env.NODE_ENV==="production",sameSite:"lax",path:"/",maxAge:0});jar.set(ARENA_COOKIE,"",{httpOnly:true,secure:process.env.NODE_ENV==="production",sameSite:"lax",path:"/",maxAge:0});}
